import { describe, expect, it } from 'vitest';
import { getFormat } from '../src/lib/formats';
import type { PackSheet, PackedItem } from '../src/lib/packer';
import type { FormatOptions } from '../src/lib/formats/types';

/**
 * Minimal sheet for code-file smoke tests: two sprites with names that exercise
 * both the `/`-path split (`hero/walk/0001`) and the identifier sanitizer
 * (`foo-bar`).
 */
function makeSheet(): PackSheet {
  const items: PackedItem[] = [
    {
      id: 'hero-id',
      name: 'hero/walk/0001',
      width: 32,
      height: 32,
      image: {} as HTMLImageElement,
      url: 'blob:hero',
      x: 0,
      y: 0,
      rotated: false,
      placed: true,
      sheetIndex: 0,
      trimmed: false,
      sourceSize: { w: 32, h: 32 },
      spriteSourceSize: { x: 0, y: 0, w: 32, h: 32 },
    },
    {
      id: 'foo-id',
      name: 'foo-bar',
      width: 16,
      height: 24,
      image: {} as HTMLImageElement,
      url: 'blob:foo',
      x: 40,
      y: 0,
      rotated: true,
      placed: true,
      sheetIndex: 0,
      trimmed: false,
      sourceSize: { w: 16, h: 24 },
      spriteSourceSize: { x: 0, y: 0, w: 16, h: 24 },
    },
  ];
  return { index: 0, width: 128, height: 128, packed: items };
}

function baseOptions(overrides: Partial<FormatOptions> = {}): FormatOptions {
  return {
    fileName: 'atlas',
    imageFileName: () => 'atlas.png',
    dataFileName: `atlas.${overrides.namespace ? 'ext' : 'ext'}`,
    scale: 1,
    ...overrides,
  };
}

describe('Swift code-file generator', () => {
  const generator = getFormat('swift');

  it('advertises the .swift extension and Swift label', () => {
    expect(generator.extension).toBe('swift');
    expect(generator.label).toBe('Swift');
  });

  it('emits the generated-by header, raw names, sanitized identifiers, and frames', () => {
    const output = generator.generate(makeSheet(), baseOptions());
    expect(output.startsWith('// Generated by Web TexturePacker on ')).toBe(true);
    expect(output).toContain('"hero/walk/0001"');
    expect(output).toContain('"foo-bar"');
    expect(output).toContain('case hero_walk_0001 = "hero/walk/0001"');
    expect(output).toContain('case foo_bar = "foo-bar"');
    // Rotated frame swaps width/height for the frame dimension.
    expect(output).toContain('Frame(x: 40, y: 0, w: 24, h: 16, rotated: true)');
    expect(output).toContain('Frame(x: 0, y: 0, w: 32, h: 32, rotated: false)');
    expect(output).toContain('public enum SpriteSheet: String');
  });

  it('honours the className override', () => {
    const output = generator.generate(makeSheet(), baseOptions({ className: 'MyAtlas' }));
    expect(output).toContain('public enum MyAtlas: String');
    expect(output).toContain('public extension MyAtlas');
    expect(output).not.toContain('public enum SpriteSheet: String');
  });

  it('falls back to sprite_<index> on all-Unicode names and deduplicates collisions', () => {
    const sheet = makeSheet();
    sheet.packed = [
      { ...sheet.packed[0], id: 'a', name: '★', x: 0, y: 0 },
      { ...sheet.packed[0], id: 'b', name: '☆', x: 40, y: 40 },
      { ...sheet.packed[0], id: 'c', name: 'hero/walk/0001', x: 80, y: 0 },
      { ...sheet.packed[0], id: 'd', name: 'hero-walk-0001', x: 80, y: 40 },
    ];
    const output = generator.generate(sheet, baseOptions());
    expect(output).toContain('case sprite_0 = "★"');
    expect(output).toContain('case sprite_1 = "☆"');
    expect(output).toMatch(/case hero_walk_0001 = "hero\/walk\/0001"/);
    expect(output).toMatch(/case hero_walk_0001_2 = "hero-walk-0001"/);
  });
});

describe('C# code-file generator', () => {
  const generator = getFormat('csharp');

  it('advertises the .cs extension and C# label', () => {
    expect(generator.extension).toBe('cs');
    expect(generator.label).toBe('C#');
  });

  it('emits the generated-by header, raw names, PascalCase constants, and switch arms', () => {
    const output = generator.generate(makeSheet(), baseOptions());
    expect(output.startsWith('// Generated by Web TexturePacker on ')).toBe(true);
    // Raw string literals are preserved for the switch cases and const values.
    expect(output).toContain('"hero/walk/0001"');
    expect(output).toContain('"foo-bar"');
    // PascalCase constants live inside the Sprites class.
    expect(output).toContain('public const string Hero_Walk_0001 = "hero/walk/0001";');
    expect(output).toContain('public const string Foo_bar = "foo-bar";');
    // Rotated frame swaps width/height for the frame dimension.
    expect(output).toContain('X = 40, Y = 0, W = 24, H = 16, Rotated = true');
    expect(output).toContain('X = 0, Y = 0, W = 32, H = 32, Rotated = false');
    // Defaults for namespace and class.
    expect(output).toContain('namespace WebTexturePacker');
    expect(output).toContain('public static class SpriteSheet');
  });

  it('honours the namespace and className overrides', () => {
    const output = generator.generate(
      makeSheet(),
      baseOptions({ namespace: 'MyGame.Atlas', className: 'HeroAtlas' }),
    );
    expect(output).toContain('namespace MyGame.Atlas');
    expect(output).toContain('public static class HeroAtlas');
    expect(output).not.toContain('namespace WebTexturePacker');
    expect(output).not.toContain('public static class SpriteSheet');
  });
});

describe('C++ code-file generator', () => {
  const generator = getFormat('cpp');

  it('advertises the .hpp extension and C++ label', () => {
    expect(generator.extension).toBe('hpp');
    expect(generator.label).toBe('C++');
  });

  it('emits the generated-by header, raw names, kPascalCase constants, and frameFor arms', () => {
    const output = generator.generate(makeSheet(), baseOptions());
    expect(output.startsWith('// Generated by Web TexturePacker on ')).toBe(true);
    expect(output).toContain('#pragma once');
    expect(output).toContain('"hero/walk/0001"');
    expect(output).toContain('"foo-bar"');
    // C++ prefixes each constant with `k` per Google style guide convention.
    expect(output).toContain('constexpr std::string_view kHero_Walk_0001 = "hero/walk/0001";');
    expect(output).toContain('constexpr std::string_view kFoo_bar = "foo-bar";');
    // frameFor returns rotated w/h swapped and a default zero frame at the tail.
    expect(output).toContain('if (name == "hero/walk/0001") return {0, 0, 32, 32, false};');
    expect(output).toContain('if (name == "foo-bar") return {40, 0, 24, 16, true};');
    expect(output).toContain('return {0, 0, 0, 0, false};');
    // Default namespace is lower_snake_case.
    expect(output).toContain('namespace webtexturepacker {');
    expect(output).toContain('}  // namespace webtexturepacker');
  });

  it('honours the namespace override', () => {
    const output = generator.generate(makeSheet(), baseOptions({ namespace: 'my_game::atlas' }));
    expect(output).toContain('namespace my_game::atlas {');
    expect(output).toContain('}  // namespace my_game::atlas');
    expect(output).not.toContain('namespace webtexturepacker {');
  });
});
