import type { FormatGenerator } from './types';

/**
 * Cocos2d-JS spritesheet as a CommonJS module. Each frame follows the
 * TexturePacker JSON-Hash convention Cocos2d-JS consumes via
 * `cc.spriteFrameCache.addSpriteFrames`, but wrapped as `module.exports = { ... }`
 * so it can be `require()`d directly from a build pipeline.
 */
const cocos2dJs: FormatGenerator = {
  extension: 'js',
  label: 'Cocos2d-JS',
  generate(sheet, opts) {
    const scale = opts.scale ?? 1;
    const frames: Record<string, unknown> = {};
    for (const item of sheet.packed) {
      const fw = item.rotated ? item.height : item.width;
      const fh = item.rotated ? item.width : item.height;
      frames[item.name] = {
        frame: { x: item.x, y: item.y, w: fw, h: fh },
        rotated: item.rotated,
        trimmed: item.trimmed,
        spriteSourceSize: { ...item.spriteSourceSize },
        sourceSize: { w: item.sourceSize.w, h: item.sourceSize.h },
      };
    }
    const body = {
      meta: {
        app: 'Web TexturePacker',
        image: opts.imageFileName(sheet.index),
        format: 'RGBA8888',
        size: { w: sheet.width, h: sheet.height },
        scale,
      },
      frames,
    };
    return `// Generated by Web TexturePacker\nmodule.exports = ${JSON.stringify(body, null, 2)};\n`;
  },
};

export default cocos2dJs;
