import type { FormatGenerator } from './types';
import { sanitizeCsharpIdentifier } from './csharp';

// Multipack note: this generator emits C++ constants for a single sheet's
// frames. When `PackResult.sheets.length > 1` the caller iterates the sheets
// itself; the file below only references the `sheet` argument passed in.

/** Escape a sprite name for use inside a C++ double-quoted string literal. */
function escapeCppString(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
}

/** Attach numeric suffixes to any duplicates so every emitted symbol is unique. */
function uniqueIdentifiers(names: string[]): string[] {
  const counts = new Map<string, number>();
  const seen = new Set<string>();
  const out: string[] = [];
  for (const name of names) {
    let candidate = name;
    if (seen.has(candidate)) {
      const nextCount = (counts.get(name) ?? 1) + 1;
      counts.set(name, nextCount);
      candidate = `${name}_${nextCount}`;
      while (seen.has(candidate)) {
        const bump = (counts.get(name) ?? 1) + 1;
        counts.set(name, bump);
        candidate = `${name}_${bump}`;
      }
    } else {
      counts.set(name, 1);
    }
    seen.add(candidate);
    out.push(candidate);
  }
  return out;
}

const cpp: FormatGenerator = {
  extension: 'hpp',
  label: 'C++',
  generate(sheet, opts) {
    const namespace =
      opts.namespace && opts.namespace.trim() !== '' ? opts.namespace : 'webtexturepacker';
    const image = opts.imageFileName(sheet.index);
    // C++ follows the same PascalCase-per-segment scheme as C#, then prefixes
    // each constant with the traditional `k` marker.
    const rawIdentifiers = sheet.packed.map(
      (item, i) => `k${sanitizeCsharpIdentifier(item.name, i)}`,
    );
    const identifiers = uniqueIdentifiers(rawIdentifiers);
    const dateIso = new Date().toISOString();

    const lines: string[] = [];
    lines.push(
      `// Generated by Web TexturePacker on ${dateIso}`,
      '// Do not edit manually.',
      '#pragma once',
      '#include <string_view>',
      '#include <cstdint>',
      '',
      `namespace ${namespace} {`,
      '',
      'struct SpriteFrame {',
      '    std::int32_t x, y, w, h;',
      '    bool rotated;',
      '};',
      '',
      `constexpr std::string_view kAtlasName = "${escapeCppString(image)}";`,
      `constexpr std::int32_t kAtlasWidth = ${sheet.width};`,
      `constexpr std::int32_t kAtlasHeight = ${sheet.height};`,
      '',
      'namespace sprites {',
    );
    for (let i = 0; i < sheet.packed.length; i++) {
      const item = sheet.packed[i];
      lines.push(
        `    constexpr std::string_view ${identifiers[i]} = "${escapeCppString(item.name)}";`,
      );
    }
    lines.push(
      '}  // namespace sprites',
      '',
      'constexpr SpriteFrame frameFor(std::string_view name) {',
    );
    for (let i = 0; i < sheet.packed.length; i++) {
      const item = sheet.packed[i];
      const fw = item.rotated ? item.height : item.width;
      const fh = item.rotated ? item.width : item.height;
      lines.push(
        `    if (name == "${escapeCppString(item.name)}") return {${item.x}, ${item.y}, ${fw}, ${fh}, ${item.rotated ? 'true' : 'false'}};`,
      );
    }
    lines.push(
      '    return {0, 0, 0, 0, false};',
      '}',
      '',
      `}  // namespace ${namespace}`,
      '',
    );
    return lines.join('\n');
  },
};

export default cpp;
