import type { FormatGenerator } from './types';

// Multipack note: this generator emits C# constants for a single sheet's
// frames. When `PackResult.sheets.length > 1` the caller iterates the sheets
// itself; the file below only references the `sheet` argument passed in.

const RESERVED_CSHARP_KEYWORDS = new Set([
  'abstract', 'as', 'base', 'bool', 'break', 'byte', 'case', 'catch', 'char',
  'checked', 'class', 'const', 'continue', 'decimal', 'default', 'delegate',
  'do', 'double', 'else', 'enum', 'event', 'explicit', 'extern', 'false',
  'finally', 'fixed', 'float', 'for', 'foreach', 'goto', 'if', 'implicit',
  'in', 'int', 'interface', 'internal', 'is', 'lock', 'long', 'namespace',
  'new', 'null', 'object', 'operator', 'out', 'override', 'params', 'private',
  'protected', 'public', 'readonly', 'ref', 'return', 'sbyte', 'sealed',
  'short', 'sizeof', 'stackalloc', 'static', 'string', 'struct', 'switch',
  'this', 'throw', 'true', 'try', 'typeof', 'uint', 'ulong', 'unchecked',
  'unsafe', 'ushort', 'using', 'virtual', 'void', 'volatile', 'while',
]);

/** Escape a sprite name for use inside a C# double-quoted string literal. */
function escapeCsharpString(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
}

/**
 * Sanitize a single path segment to a PascalCase C# identifier fragment.
 * Non-identifier characters collapse to `_`; the first character is capitalised
 * so segments like `hero` become `Hero` while numeric suffixes like `0001`
 * remain untouched.
 */
function sanitizeSegment(segment: string): string {
  let cleaned = '';
  for (const ch of segment) {
    if (/[A-Za-z0-9_]/.test(ch)) cleaned += ch;
    else cleaned += '_';
  }
  cleaned = cleaned.replace(/_+/g, '_');
  if (cleaned === '' || cleaned === '_') return '';
  const first = cleaned.charAt(0);
  if (/[A-Za-z]/.test(first)) return first.toUpperCase() + cleaned.slice(1);
  return cleaned;
}

/**
 * Convert a raw sprite name into a valid C# identifier.
 *   - Split on `/` and PascalCase each segment.
 *   - Join with `_` (matches the P3-06 sanitizer table).
 *   - Leading digit gets an `_` prefix.
 *   - Reserved keyword collides get an `_` prefix.
 *   - Empty result (e.g. all-Unicode name) → `Sprite_<index>` fallback.
 */
function sanitizeCsharpIdentifier(name: string, index: number): string {
  const segments = name.split('/').map(sanitizeSegment).filter((seg) => seg.length > 0);
  let identifier = segments.join('_');
  if (identifier === '' || identifier === '_') return `Sprite_${index}`;
  if (/^[0-9]/.test(identifier)) identifier = `_${identifier}`;
  if (RESERVED_CSHARP_KEYWORDS.has(identifier)) identifier = `_${identifier}`;
  return identifier;
}

/** Attach numeric suffixes to any duplicates so every emitted constant is unique. */
function uniqueIdentifiers(names: string[]): string[] {
  const counts = new Map<string, number>();
  const seen = new Set<string>();
  const out: string[] = [];
  for (const name of names) {
    let candidate = name;
    if (seen.has(candidate)) {
      const nextCount = (counts.get(name) ?? 1) + 1;
      counts.set(name, nextCount);
      candidate = `${name}_${nextCount}`;
      while (seen.has(candidate)) {
        const bump = (counts.get(name) ?? 1) + 1;
        counts.set(name, bump);
        candidate = `${name}_${bump}`;
      }
    } else {
      counts.set(name, 1);
    }
    seen.add(candidate);
    out.push(candidate);
  }
  return out;
}

const csharp: FormatGenerator = {
  extension: 'cs',
  label: 'C#',
  generate(sheet, opts) {
    const namespace =
      opts.namespace && opts.namespace.trim() !== '' ? opts.namespace : 'WebTexturePacker';
    const className =
      opts.className && opts.className.trim() !== '' ? opts.className : 'SpriteSheet';
    const image = opts.imageFileName(sheet.index);
    const rawIdentifiers = sheet.packed.map((item, i) => sanitizeCsharpIdentifier(item.name, i));
    const identifiers = uniqueIdentifiers(rawIdentifiers);
    const dateIso = new Date().toISOString();

    const lines: string[] = [];
    lines.push(
      `// Generated by Web TexturePacker on ${dateIso}`,
      '// Do not edit manually.',
      '',
      `namespace ${namespace}`,
      '{',
      `    public static class ${className}`,
      '    {',
      `        public const string AtlasName = "${escapeCsharpString(image)}";`,
      `        public const int AtlasWidth = ${sheet.width};`,
      `        public const int AtlasHeight = ${sheet.height};`,
      '',
      '        public struct Frame',
      '        {',
      '            public int X, Y, W, H;',
      '            public bool Rotated;',
      '        }',
      '',
      '        public static class Sprites',
      '        {',
    );
    for (let i = 0; i < sheet.packed.length; i++) {
      const item = sheet.packed[i];
      lines.push(
        `            public const string ${identifiers[i]} = "${escapeCsharpString(item.name)}";`,
      );
    }
    lines.push(
      '        }',
      '',
      '        public static Frame GetFrame(string name)',
      '        {',
      '            switch (name)',
      '            {',
    );
    for (let i = 0; i < sheet.packed.length; i++) {
      const item = sheet.packed[i];
      const fw = item.rotated ? item.height : item.width;
      const fh = item.rotated ? item.width : item.height;
      lines.push(
        `                case "${escapeCsharpString(item.name)}": return new Frame { X = ${item.x}, Y = ${item.y}, W = ${fw}, H = ${fh}, Rotated = ${item.rotated ? 'true' : 'false'} };`,
      );
    }
    lines.push(
      '                default: throw new System.ArgumentException("Unknown sprite: " + name);',
      '            }',
      '        }',
      '    }',
      '}',
      '',
    );
    return lines.join('\n');
  },
};

export default csharp;
export { sanitizeCsharpIdentifier };
