import type { FormatGenerator } from './types';

// Multipack note: this generator emits Swift constants for a single sheet's
// frames. When `PackResult.sheets.length > 1` the caller iterates the sheets
// itself; the file below only references the `sheet` argument passed in.

const RESERVED_SWIFT_KEYWORDS = new Set([
  'associatedtype', 'class', 'deinit', 'enum', 'extension', 'fileprivate',
  'func', 'import', 'init', 'inout', 'internal', 'let', 'open', 'operator',
  'private', 'protocol', 'public', 'rethrows', 'static', 'struct', 'subscript',
  'typealias', 'var', 'break', 'case', 'continue', 'default', 'defer', 'do',
  'else', 'fallthrough', 'for', 'guard', 'if', 'in', 'repeat', 'return',
  'switch', 'where', 'while', 'as', 'catch', 'false', 'is', 'nil', 'super',
  'self', 'Self', 'throw', 'throws', 'true', 'try',
]);

/** Escape a sprite name for use inside a Swift double-quoted string literal. */
function escapeSwiftString(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
}

/**
 * Convert a raw sprite name into a valid Swift identifier.
 *
 * Sanitization rules (matches the P3-06 sanitizer table):
 *   - `/`, `-`, `.`, spaces → `_`
 *   - any other char outside [A-Za-z0-9_] → `_`
 *   - a leading digit gets an `_` prefix
 *   - a Swift reserved word gets an `_` prefix
 *   - if the sanitized identifier is empty (e.g. all Unicode), fall back to
 *     `sprite_<index>` so the emitter never throws on non-ASCII input.
 */
function sanitizeSwiftIdentifier(name: string, index: number): string {
  let identifier = '';
  for (const ch of name) {
    if (/[A-Za-z0-9_]/.test(ch)) identifier += ch;
    else if (ch === '/' || ch === '-' || ch === '.' || ch === ' ') identifier += '_';
    else identifier += '_';
  }
  identifier = identifier.replace(/_+/g, '_');
  if (identifier === '' || identifier === '_') return `sprite_${index}`;
  if (/^[0-9]/.test(identifier)) identifier = `_${identifier}`;
  if (RESERVED_SWIFT_KEYWORDS.has(identifier)) identifier = `_${identifier}`;
  return identifier;
}

/** Attach numeric suffixes to any duplicates so every emitted case is unique. */
function uniqueIdentifiers(names: string[]): string[] {
  const counts = new Map<string, number>();
  const seen = new Set<string>();
  const out: string[] = [];
  for (const name of names) {
    let candidate = name;
    if (seen.has(candidate)) {
      const nextCount = (counts.get(name) ?? 1) + 1;
      counts.set(name, nextCount);
      candidate = `${name}_${nextCount}`;
      while (seen.has(candidate)) {
        const bump = (counts.get(name) ?? 1) + 1;
        counts.set(name, bump);
        candidate = `${name}_${bump}`;
      }
    } else {
      counts.set(name, 1);
    }
    seen.add(candidate);
    out.push(candidate);
  }
  return out;
}

const swift: FormatGenerator = {
  extension: 'swift',
  label: 'Swift',
  generate(sheet, opts) {
    const enumName = opts.className && opts.className.trim() !== '' ? opts.className : 'SpriteSheet';
    const image = opts.imageFileName(sheet.index);
    const rawIdentifiers = sheet.packed.map((item, i) => sanitizeSwiftIdentifier(item.name, i));
    const identifiers = uniqueIdentifiers(rawIdentifiers);
    const dateIso = new Date().toISOString();

    const lines: string[] = [];
    lines.push(
      `// Generated by Web TexturePacker on ${dateIso}`,
      '// Do not edit manually.',
      'import Foundation',
      '',
      `public enum ${enumName}: String {`,
      `    public static let atlasName = "${escapeSwiftString(image)}"`,
      `    public static let atlasWidth: Int = ${sheet.width}`,
      `    public static let atlasHeight: Int = ${sheet.height}`,
      '',
    );
    for (let i = 0; i < sheet.packed.length; i++) {
      const item = sheet.packed[i];
      lines.push(`    case ${identifiers[i]} = "${escapeSwiftString(item.name)}"`);
    }
    lines.push(
      '}',
      '',
      `public extension ${enumName} {`,
      '    struct Frame { public let x, y, w, h: Int; public let rotated: Bool }',
      '    var frame: Frame {',
      '        switch self {',
    );
    for (let i = 0; i < sheet.packed.length; i++) {
      const item = sheet.packed[i];
      const fw = item.rotated ? item.height : item.width;
      const fh = item.rotated ? item.width : item.height;
      lines.push(
        `        case .${identifiers[i]}: return Frame(x: ${item.x}, y: ${item.y}, w: ${fw}, h: ${fh}, rotated: ${item.rotated ? 'true' : 'false'})`,
      );
    }
    lines.push(
      '        }',
      '    }',
      '}',
      '',
    );
    return lines.join('\n');
  },
};

export default swift;
export { sanitizeSwiftIdentifier, uniqueIdentifiers };
